### ISSUE TITLE
Openrefine reconciliation service "search for match" does not find an entry that exists at ror.org/03cpyc314  but openrefine reconciliation service doesnt show that entry

### ISSUE THREAD

**Issue by aarontaycheehsien** [ror-community/ror-reconciler#8]
Was trying the "Search for match" since the bug was fixed for https://github.com/ror-community/ror-reconciler/issues/6 .

However, while the search generally works , I'm still not able to find the entry at https://ror.org/03cpyc314 even searching by the exact name National Research Foundation

Action taken

1. Click on "Search for match"
2. In search box, type National Research Foundation

Observed behavior

1. Entry does not appear as option for https://ror.org/03cpyc314

Expected behavior

1. To see option for https://ror.org/03cpyc314

**Comment by adam-earthscope** [comment]
I'm not sure whether these are the same bug, but I've run into a number of similar cases where an exact match for the name doesn't turn up an entry:

"University of Leicester" (https://ror.org/04h699437)
"University of Trieste" (https://ror.org/02n742c10)
"University of Zagreb" (https://ror.org/00mv6sv71)

Oddly, mixing up the name often succeeds, eg. "zagreb university" finds the correct entry.

**Comment by mariagould** [comment]
Thanks for these examples. @dtkaczyk has been working on search & querying so I am looping her in.

**Comment by mariagould** [comment]
This bug should be fixed but please let us know if not.
